<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is provided with Magento in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Copyright © MultiSafepay, Inc. All rights reserved.
 * See DISCLAIMER.md for disclaimer details.
 */

declare(strict_types=1);

/** @var Template $block */
/** @var MultiSafepayPaymentComponent $magewire */
/** @var Escaper $escaper */

use MultiSafepay\HyvaCheckout\Payment\Method\MultiSafepayPaymentComponent;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<script>
    window.addEventListener('checkout:payment:method-activate', event => {
        console.log('checkout:payment:method-activate payment_component_after.phtml', event.detail.method);

        let paymentComponent;

        if (event.detail.method !== '<?= $escaper->escapeJs($magewire->getMethodCode()) ?>' ||
            !document.getElementById('multisafepay-<?= $escaper->escapeHtmlAttr($magewire->getMethodCode()) ?>-component')){
            return;
        }

        hyvaCheckout.payment.activate('<?= $escaper->escapeJs($magewire->getMethodCode())?>', {
            async initialize() {
                let recurringData;

                let orderData = {
                    currency: '<?= $escaper->escapeJs($magewire->getCurrency()) ?>',
                    amount: '<?= $escaper->escapeJs($magewire->getAmount()) ?>',
                    template: {
                        settings: {
                            embed_mode: true,
                        },
                    },
                    customer: {
                        locale: '<?= $escaper->escapeJs($magewire->getLocale()) ?>',
                        country: '<?= $escaper->escapeJs($magewire->getCountry()) ?>'
                    }
                }

                <?php if ($magewire->getTokens()) { ?>
                recurringData = {
                    model: 'cardOnFile',
                    tokens: <?= $magewire->getTokens() ?>
                }
                <?php } ?>

                let paymentComponentData = {
                    env: '<?= $escaper->escapeJs($magewire->getEnvironment()) ?>',
                    apiToken: '<?= $escaper->escapeJs($magewire->getApiToken()) ?>',
                    order: orderData
                };

                if (recurringData) {
                    paymentComponentData.recurring = recurringData;
                }

                paymentComponent = new MultiSafepay(paymentComponentData);

                paymentComponent.init('payment', {
                    container: '#multisafepay-<?= $escaper->escapeJs($magewire->getMethodCode()) ?>-component',
                    gateway: '<?= $escaper->escapeJs($magewire->getGatewayCode()) ?>',
                    onError: state => {
                        console.log('onError', state);
                    }
                })
            }
        });
    }, {once: true})
</script>
<?php isset($hyvaCsp) && $hyvaCsp->registerInlineScript() ?>
