<?php
/**
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is provided with Magento in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * Copyright © MultiSafepay, Inc. All rights reserved.
 * See DISCLAIMER.md for disclaimer details.
 */

declare(strict_types=1);

/** @var Template $block */
/** @var MultiSafepayPaymentComponent $magewire */
/** @var Escaper $escaper */

use MultiSafepay\HyvaCheckout\Payment\Method\MultiSafepayPaymentComponent;
use Magento\Framework\Escaper;
use Magento\Framework\View\Element\Template;

?>
<div class="col-span-6" wire:payment-method="multisafepay_creditcard">
    <?php if ($magewire->isPaymentComponentEnabled()) {?>
    <div id="multisafepay-<?= $escaper->escapeHtmlAttr($magewire->getMethodCode()) ?>-component" class="multisafepay-payment-component" wire:ignore></div>
    <?php } ?>
</div>
